create database countries;
use countries;
CREATE TABLE STATE_INFO(
ID INT,
NAME VARCHAR(10),
CAPITAL VARCHAR(12)
);

INSERT INTO STATE_INFO(ID,NAME,CAPITAL)VALUES(1,'KARNATAKA','BENGLORE');

CREATE TABLE CITY_INFO(
ID INT,
NAME VARCHAR(9),
STATENAME VARCHAR(13)
);

INSERT INTO CITY_INFO(ID,NAME,STATENAME)VALUES(2,'BENGLORE','KARNATAKA');

SELECT * FROM STATE_INFO;
SELECT * FROM CITY_INFO;